services:
  faces:
    build:
      context: ./FACES.Source
      dockerfile: Dockerfile
    volumes:
      - ./config/.dataprotection-keys:/root/.aspnet/DataProtection-Keys
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=mydatabase;Username=myuser;Password=mypassword


  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    build:
      context: ./config/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/certs:/etc/letsencrypt
    depends_on:
      - faces

volumes:
  postgres_data:
